{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "d8426327-4454-4148-93fd-7257aff3d928",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "=======================================================\n",
      " [ML1] get_prompt_score 분포 분석 (총 1736개 문항)\n",
      "=======================================================\n",
      "\n",
      "1. 주요 통계치:\n",
      "  - 평균 점수 (Mean): 0.2580\n",
      "  - 중앙값 (Median):   0.1824\n",
      "  - 최소값 / 최대값:   0.0474 / 0.9890\n",
      "\n",
      "2. ML2 연계 추천 임계값(Threshold) 컷오프:\n",
      "  - [하위 54% 컷] Easy (Light 전담 구간):   score < 0.1824\n",
      "  - [중간 21% 구간] Medium (ax31 배정 구간): 0.1824 <= score < 0.3208\n",
      "  - [상위 25% 컷] Hard (Think 승격 구간):   score >= 0.3208\n",
      "  - [상위 15% 컷] Ultra (초고난도 Think):   score >= 0.5000\n",
      "\n",
      "3. 구간별 실제 문항 배정 수:\n",
      "  - Light 영역 (하위 54%): 722개 (41.6%)\n",
      "  - Base 영역  (중간 21%): 527개 (30.4%)\n",
      "  - Think 영역 (상위 25%): 487개 (28.1%)\n",
      "=======================================================\n"
     ]
    }
   ],
   "source": [
    "import json\n",
    "import sys\n",
    "from pathlib import Path\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "# src 폴더 경로를 파이썬 모듈 검색 경로에 추가\n",
    "sys.path.insert(0, \"src\")\n",
    "\n",
    "from ossp_router.heuristic import get_prompt_score\n",
    "from ossp_router.protocol import Episode\n",
    "\n",
    "# 1. train 데이터 로드\n",
    "with open(\"data/train/inputs-base.json\", \"r\", encoding=\"utf-8\") as f:\n",
    "    raw_data = json.load(f)\n",
    "\n",
    "# 리스트 또는 딕셔너리 형태 안전 파싱\n",
    "episodes_raw = raw_data.get(\"episodes\", raw_data) if isinstance(raw_data, dict) else raw_data\n",
    "\n",
    "scores = []\n",
    "lengths = []\n",
    "\n",
    "for item in episodes_raw:\n",
    "    if isinstance(item, str):\n",
    "        item = json.loads(item)\n",
    "    \n",
    "    # Episode 객체 생성\n",
    "    prompt = item.get(\"prompt\")\n",
    "    messages = item.get(\"messages\")\n",
    "    episode = Episode(\n",
    "        episode_id=item.get(\"episode_id\", \"\"),\n",
    "        prompt=prompt,\n",
    "        messages=messages\n",
    "    )\n",
    "    \n",
    "    # ML1 점수 계산\n",
    "    score = get_prompt_score(episode)\n",
    "    scores.append(score)\n",
    "    \n",
    "    text = prompt if prompt else \" \".join([m.get(\"content\", \"\") for m in (messages or [])])\n",
    "    lengths.append(len(text))\n",
    "\n",
    "df = pd.DataFrame({\"score\": scores, \"length\": lengths})\n",
    "\n",
    "# 2. 분위수(Percentile) 계산\n",
    "print(\"=\" * 55)\n",
    "print(f\" [ML1] get_prompt_score 분포 분석 (총 {len(df)}개 문항)\")\n",
    "print(\"=\" * 55)\n",
    "\n",
    "print(\"\\n1. 주요 통계치:\")\n",
    "print(f\"  - 평균 점수 (Mean): {df['score'].mean():.4f}\")\n",
    "print(f\"  - 중앙값 (Median):   {df['score'].median():.4f}\")\n",
    "print(f\"  - 최소값 / 최대값:   {df['score'].min():.4f} / {df['score'].max():.4f}\")\n",
    "\n",
    "# ML2 팀원의 비율과 매핑되는 분위수\n",
    "p54 = np.percentile(df[\"score\"], 54)\n",
    "p75 = np.percentile(df[\"score\"], 75)\n",
    "p85 = np.percentile(df[\"score\"], 85)\n",
    "\n",
    "print(\"\\n2. ML2 연계 추천 임계값(Threshold) 컷오프:\")\n",
    "print(f\"  - [하위 54% 컷] Easy (Light 전담 구간):   score < {p54:.4f}\")\n",
    "print(f\"  - [중간 21% 구간] Medium (ax31 배정 구간): {p54:.4f} <= score < {p75:.4f}\")\n",
    "print(f\"  - [상위 25% 컷] Hard (Think 승격 구간):   score >= {p75:.4f}\")\n",
    "print(f\"  - [상위 15% 컷] Ultra (초고난도 Think):   score >= {p85:.4f}\")\n",
    "\n",
    "print(\"\\n3. 구간별 실제 문항 배정 수:\")\n",
    "easy_cnt = (df[\"score\"] < p54).sum()\n",
    "hard_cnt = (df[\"score\"] >= p75).sum()\n",
    "med_cnt = len(df) - easy_cnt - hard_cnt\n",
    "print(f\"  - Light 영역 (하위 54%): {easy_cnt}개 ({easy_cnt/len(df)*100:.1f}%)\")\n",
    "print(f\"  - Base 영역  (중간 21%): {med_cnt}개 ({med_cnt/len(df)*100:.1f}%)\")\n",
    "print(f\"  - Think 영역 (상위 25%): {hard_cnt}개 ({hard_cnt/len(df)*100:.1f}%)\")\n",
    "print(\"=\" * 55)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bbf58125-f23c-49c1-b76b-0dd8a413fef4",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
